=== martinfmi/smarthome/bundles/config/org.eclipse.smarthome.config.setup/org.eclipse.smarthome.config.setup.schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:setup-flow="http://eclipse.org/smarthome/schemas/config/setup-flow/v0.0.1" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://eclipse.org/smarthome/schemas/config/setup-flow/v0.0.1">
	<!-- 'setup-flows' root type definition -->
	<xs:element name="setup-flows">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="setup-flow" type="setup-flow:setupFlow" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- 'setup-flow' root type definition -->
	<xs:element name="setup-flow" type="setup-flow:setupFlow"/>
	<!-- 'setup-flow' type definition -->
	<xs:complexType name="setupFlow">
		<xs:sequence>
			<xs:element name="thing-types" type="setup-flow:thingTypes"/>
			<xs:element name="steps" type="setup-flow:setupSteps"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="bindingId" type="xs:string" use="required"/>
	</xs:complexType>
	<!-- 'thing-types' type definition -->
	<xs:complexType name="thingTypes">
		<xs:sequence>
			<xs:element name="thing-type" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<!-- 'steps' type definition -->
	<xs:complexType name="setupSteps">
		<xs:choice minOccurs="1" maxOccurs="unbounded">
			<xs:element name="search-step" type="setup-flow:searchStep"/>
			<xs:element name="external-event-step" type="setup-flow:externalEventStep"/>
			<xs:element name="configuration-step" type="setup-flow:configurationStep"/>
		</xs:choice>
	</xs:complexType>
	<!-- 'step' base-type definition -->
	<xs:complexType name="setupStep">
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
	<!-- 'search-step' type definition -->
	<xs:complexType name="searchStep">
		<xs:complexContent>
			<xs:extension base="setup-flow:setupStep">
				<xs:sequence>
					<xs:element name="timeout" type="setup-flow:timeout"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- 'external-event-step' type definition -->
	<xs:complexType name="externalEventStep">
		<xs:complexContent>
			<xs:extension base="setup-flow:setupStep">
				<xs:sequence>
					<xs:element name="timeout" type="setup-flow:timeout"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- 'configuration-step' type definition -->
	<xs:complexType name="configurationStep">
		<xs:complexContent>
			<xs:extension base="setup-flow:setupStep">
				<xs:sequence>
					<xs:element name="properties" type="setup-flow:properties"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- 'properties' type definition -->
	<xs:complexType name="properties">
		<xs:sequence>
			<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<!-- 'timeout' type definition -->
	<xs:simpleType name="timeout">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="-1"/>
			<xs:maxInclusive value="86400"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== martinfmi/smarthome/bundles/config/org.eclipse.smarthome.config.setup/example/hue.xml
<?xml version="1.0" encoding="UTF-8"?>

<setup-flow:setup-flow id="flow-hue" bindingId="hue"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:setup-flow="http://eclipse.org/smarthome/schemas/config/setup-flow/v0.0.1"
        xsi:schemaLocation="http://eclipse.org/smarthome/schemas/config/setup-flow/v0.0.1 org.eclipse.smarthome.config.setup.schema.xsd">

    <thing-types>
        <thing-type>HueGateway</thing-type>
    </thing-types>

    <steps>
        <search-step id="upnpSearch">
            <timeout>60</timeout>
        </search-step>

        <configuration-step id="ipConfiguration">
            <properties>
                <property name="ip" />
            </properties>
        </configuration-step>

        <configuration-step id="secretConfiguration">
            <properties>
                <property name="secret" />
            </properties>
        </configuration-step>

        <external-event-step id="pairing">
            <timeout>180</timeout>
        </external-event-step>
    </steps>

</setup-flow:setup-flow>
